project_id = "csmlycqkkbaluurwywzw"

[auth]
enabled = true
site_url = "https://localhost:3000"
additional_redirect_urls = ["https://lovable.dev"]

[auth.external.google]
enabled = false
client_id = ""
secret = ""

[auth.external.github]
enabled = false
client_id = ""
secret = ""

[functions.voice-to-text]
verify_jwt = true

[functions.text-to-voice]
verify_jwt = true

[functions.ai-wellness-chat]
verify_jwt = true

[functions.ai-content-generator]
verify_jwt = true