// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://csmlycqkkbaluurwywzw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNzbWx5Y3Fra2JhbHV1cnd5d3p3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MjE2NTcsImV4cCI6MjA3MDQ5NzY1N30.J1uG2Ki7Q_nbPpEvsp81n4W_fUdjfMX-bp9pWo6dIGI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});